### ISSUE TITLE
Addition of User Search Functionality in Friends Section

### ISSUE THREAD

**Issue by DaniaHsm** [rilling/OpenTracks-Winter-2024-COMP-354#134]
Description:
Introduce a search bar at the top of the Friends page in our ski app, which allows users to search for any user on the platform. This feature will facilitate easier navigation and interaction within the app's social components.

Expected Outcomes:
Users should be able to type in the name or username of any user in the platform to locate and interact with their profiles. This feature will enhance the social functionality of the app by streamlining the process of managing social connections.

Alternatives:
As an alternative to a static search bar, consider an expandable search field that appears upon interaction to keep the interface clean and uncluttered.

Completeness Requirements:
The search bar should be clearly visible and accessible on the Friends page.
Searching should be responsive and capable of handling a large user base with minimal latency.
Appropriate testing should be conducted to ensure that users can be searched and added or removed from the friend list successfully.
The new feature should integrate seamlessly with the existing app features without disrupting the user experience.

**Comment by DaniaHsm** [comment]
Search bar was added to the newly implemented friends page.

**Comment by Zigzaw** [comment]
Worked on the searchbar and display of the friends items list which depends on the input text in the searchbar.
