### ISSUE TITLE
[UI/User Profile] Add Functionality to Set Profile Picture in User Profile Page

### ISSUE THREAD

**Issue by Rain1296** [rilling/OpenTracks-Winter-2024-COMP-354#2]
# Feature Request

- Users often seek personalization options within the app to customize their profiles and enhance their user experience. Being able to set a profile picture is a common feature across many platforms, allowing users to express themselves visually.

# Proposed Solution

- Implement functionality for a user to set his profile picture from the camera or gallery of the device.
- There should be an option to change the profile picture when editing the profile and the app should request necessary permissions to access the camera and photo gallery.
- The app should automatically resize the selected image to be used as a profile picture to fit the area on the user profile page.

# Completeness Requirements

- The UI for setting the profile picture should blend seamlessly with the user profile page layout.
- Users should be prompted with clear instructions and options to either capture a new photo using the camera or select an existing photo from their device's gallery.
- The app should request appropriate permissions to access the camera and photo gallery.
- Images selected or captured should be resized automatically so that it fits within the dimensions of the profile picture display area which will provide a uniform and better user experience.

# Alternatives

- An alternative approach may involve providing preset avatars or icons for users to choose from if they prefer not to upload a personal photo.
- Consider implementing additional features such as image cropping or filters to further enhance user customization options.

**Comment by meliimoon** [comment]
Feature has been successfully implemented.

- New option to edit the Profile Picture in the user profile page
- Permission requests implemented to receive user's permission to access device's camera and gallery. User is unable to change their profile picture without granting these permissions first
- Newest photos chosen as the profile photo get saved in internal storage and stay persistent in the profile page


![EditingProfilePictureFeature](https://github.com/rilling/OpenTracks-Winter-2024-COMP-354/assets/118542902/720e394e-1820-48d5-8de6-9a989ad48b76)
