### ISSUE TITLE
Specifying Start of Ski Season

### ISSUE THREAD

**Issue by saqpasse** [rilling/OpenTracks-Winter-2024-COMP-354#22]
**Feature Request**

Currently, there is no way to group all of my ski sessions under a single ski season. I want to be able to view all the times I went skiing in a single season and compare my skiing sessions across different seasons to track my progress on a seasonal basis.

**Proposed Solution**

Ideally, there would be a feature allowing me to select the start of a new ski season, with every ski session recorded under the ski season starting from the date I specified. If I begin a new skiing season, I should be able to group my ski sessions under this new season.

**Alternative Solutions**

Another solution could be to implement a feature for selecting a range of dates, where you choose a start date and an end date, and then all your skiing sessions would be visible within these dates. However, the proposed solution is preferable since users might not always remember when they stopped skiing. It's simpler to start a new skiing season and have the app automatically record the sessions.

**Completeness Requirements**

Verification can be easily conducted by starting a new season, recording a new session, and checking if the recorded session appears under the new season.

**Comment by mBeir96** [comment]
Test
