### ISSUE TITLE
Implement Maintenance Notifications for Sharpening and Waxing

### ISSUE THREAD

**Issue by Yushanai** [rilling/OpenTracks-Winter-2024-COMP-354#23]
### **Feature Request** 

Implementation of a notification system that alerts users about ski maintenance tasks based on their individual settings and usage is required. Notifications should be triggered based on the percentage of the interval reached for sharpening and waxing, as well as a time-based reminder if the interval has not been reached within 10 months.

### **Expected Outcome**

- Users receive timely in-app notifications when they approach the maintenance threshold for both sharpening and waxing (e.g., 90% of the set interval).
- Users receive a notification if the maintenance interval is not reached within 10 months, prompting them to perform maintenance regardless of the distance skied.

### **Alternative Solution**

- Sending email reminders in addition to in-app notifications.

### **Verification**

- User acceptance testing to validate that notifications are clear and timely.
- Unit tests to confirm that notifications are scheduled and triggered correctly based on user data.

**Comment by tristanjudd** [comment]
Notifications are now displayed in the Aggregated Statistics screen.
