### ISSUE TITLE
[User Profile/Social] Add General User Information to User Profile

### ISSUE THREAD

**Issue by JamesMolinari** [rilling/OpenTracks-Winter-2024-COMP-354#3]
Feature Request
-----------------------------------------------------------------------------------------------------------------------------------

- The feature suggests integrating comprehensive user information management into the user profile feature. This enhancement is designed to elevate user experience by fostering a deeper sense of personalization and engagement within the app ecosystem. The envisioned user information encompasses key aspects such as nickname, profile picture, date of birth, gender, height, weight, location, and an option for users to selectively share their details, should they choose to do so.

Expected Outcomes
----------------------------------------------------------------------------------------------------------

- Upon navigating to the user profile page, users will be prompted to set up, view, or modify their personal information seamlessly.
- Users will have the autonomy to share curated details via social platforms or leaderboards, offering them a platform for connection and recognition within the community.

Alternatives
----------------------------------------------------------------------------------------------------------

- Provide the user the flexibility and convenience of a ‘maybe later’ button upon being prompted with user profile creation.

Completeness Requirements
----------------------------------------------------------------------------------------------------------

- Users are prompted to create a user profile if one has not been established.
- The user profile page encompasses essential fields including nickname, profile picture, date of birth, gender, height (with default units pre-set by the app), weight (with default units), and location (with Canada prioritized at the top).Users should be able to view/edit their information.
- Users are empowered to effortlessly view and modify their profile information.
- Implementation of validation measures to ensure the accuracy and sensibility of user-entered data, particularly for fields like height, weight, and date of birth.
- Provision of a mechanism for users to share selectively curated information, fostering a sense of community engagement and connection.

**Comment by tinatsl** [comment]
Features successfully implemented:

- User sees overview of user profile and required information
- User can allow to share information on leaderboard or edit details 
- Support for units added 

![UserProfile](https://github.com/rilling/OpenTracks-Winter-2024-COMP-354/assets/91174232/c5e2b186-8ff3-431b-9348-fab46194a998)
![AllowShare](https://github.com/rilling/OpenTracks-Winter-2024-COMP-354/assets/91174232/0e6e029e-04cb-4fae-b9f6-26d250a85cd8)

Improvements to these features are planned for next sprint after connecting to database.
