### ISSUE TITLE
"Default units and activity" functionality in Settings

### ISSUE THREAD

**Issue by kevinqtra** [rilling/OpenTracks-Winter-2024-COMP-354#32]
# Problem
Recording exercises that are too short poses a significant challenge as it floods the database with irrelevant data. When users engage in brief activities like short stretches or quick movements, these instances clutter the database alongside more substantial exercises, resulting in disorganization. This clutter not only obscures meaningful data but also complicates users' ability to navigate their exercise history and derive insights. Additionally, the abundance of short exercise entries dilutes the overall dataset, potentially distorting any analysis or trends derived from the data. Consequently, users may struggle to sift through an abundance of inconsequential entries, undermining the utility and reliability of the exercise tracking application. 

# Feature Request
Implement a functionality in settings to automatically discard recorded exercises shorter than 5 sec, 10 sec, 15 sec or a user-specified duration.

# Proposed Solution
The proposed solution aims to enhance the exercise tracking functionality by providing users with the ability to automatically discard recorded exercises that are shorter than a specified duration. This feature will be integrated into the settings menu, allowing users to customize the minimum duration threshold according to their preferences.

Key Components:
1. **Settings Menu Enhancement:** Integrate a new section within the settings menu specifically for exercise tracking preferences. Add options for configuring the minimum duration threshold for recorded exercises.
2. **Minimum Duration Options:** Provide predefined duration options such as 5 sec, 10 sec, and 15 sec. Allow users to set a custom duration threshold if none of the predefined options suit their needs.
3. **Automatic Discarding Functionality:** Implement logic within the application to automatically discard recorded exercises that fall below the specified duration threshold. Upon completing an exercise tracking session, the system checks the duration of the recorded exercise. If the duration is shorter than the specified threshold, the exercise is flagged for automatic discarding.

# Alternatives
- Integrating the record saving and record time settings into separate sections of the settings menu.
- Providing additional customization options, such as setting default units and activity types.
- Implementing the option to discard the recording at the same time as the Start/Stop options.

# Completeness Requirements
- The feature will be considered complete when users can access and modify settings related to exercise tracking, including options for saving recorded exercises and displaying elapsed time.
- Settings modifications should be reflected in the tracking functionality, ensuring that recorded exercises are saved according to user preferences, the timer accurately reflects the selected time display option, and recordings below the threshold are discarded without appearing elsewhere in the application.

**Comment by e3ham** [comment]
Issue closed, all implementation was done in sprint 3.
