### ISSUE TITLE
Implement a Socials Button on the status bar - Group 15

### ISSUE THREAD

**Issue by SophiaClifton** [rilling/OpenTracks-Winter-2024-COMP-354#45]
### Feature Request
This feature involves the addition and implemetation of a Socials button on status bar of the app. When the user clicks on the Socials tab/button, it takes them to the Socials section of the app where the user can add/remove friends, view their friends data and more. The Socials section will also contain the menu/status bar so that users can navigate easily through the app.

### Expected Outcomes
The expected outcome is that users will be able to easily navigate in and out of the Socials section of the app.

### Alternatives
Instead of including the Socials button on the status/menu bar, we could include it as a seperate button on the app.

### Completeness Requirements
Ensure that the Socials button is visible on the status/menu bar.
Test that clicking the Socials button brings the user to the social section.
Test that clicking another button on the status/menu bar when inside the Socials section navigates the user to that section.

**Comment by Zigzaw** [comment]
The Social button with the friends icon has been implemented. The button leads to the Friends page, which now contains a search button, an invite button and a search bar.

**Comment by SophiaClifton** [comment]
Spcial button has been implemented.
