### ISSUE TITLE
Leaderboard Section UI

### ISSUE THREAD

**Issue by sirfootie** [rilling/OpenTracks-Winter-2024-COMP-354#49]
### Description
 Implement a leaderboard feature within the mobile app that displays the ranking of users based on: distance traveled, speed, and total time of the activity. Access to feature will be put on the navigation bar.
### Expected Outcome
A user-friendly leaderboard that will allow users to view their position in a global and local leaderboard for select activities. With a variety filters based on the metrics recorded.

### Alternative Solutions:
A possible alternative to a leaderboard is individual progress tracker. Focus on individual user progress instead of comparisons with others. This can be achieved through personalized dashboards, streaks, and badges to celebrate individual achievements.

### Verification of Completeness/Correctness:
Testing: Conduct user testing to gather feedback on the leaderboard's design, functionality, and user experience.
Data Validation: Ensure the correct data is being displayed and ranking calculations through comparisons to where data is being pulled from.

**Comment by Picard4** [comment]
Spring 2 update: We have a basic UI with test data ready to go, though the finer specifics such as Global/Friends only and the exact stats that we plan to track will need to wait until the Group 13 has the database in a more ready state.

**Comment by Picard4** [comment]
Our UI was effectively finalized by the end of Sprint 3. It is hard to call this issue truly resolved since the GUI will always need to be modified for one reason or another for as long as an app is maintained, but in the context of this class, this issue is resolved.
