### ISSUE TITLE
Leaderboard Refresh Capability

### ISSUE THREAD

**Issue by jeremy1399** [rilling/OpenTracks-Winter-2024-COMP-354#54]
**Description**
Add functionality for users to see updated leaderboard data without manual intervention or navigating away. This includes:
Automatic Refresh: Automatically refresh leaderboard data on initial load.
Manual Refresh Button: Allow users to refresh data at will via a refresh button.

**Expected Results**
Users receive the most current leaderboard standings, enhancing engagement and satisfaction.
Manual refresh gives users control over data updates without interrupting their experience.

**Alternative Solutions**
Push Notifications: Dismissed due to potential notification fatigue.
Periodic Auto-Refresh: Considered less user-friendly due to potential disruptions.

**Verify its completeness/correctness**
Evaluate the impact on app performance, focusing on load times and responsiveness, to ensure the refresh action is efficient and does not degrade user experience.

**Comment by Picard4** [comment]
The back-end for this feature is ready to go! The front-end (which Maxwell is working on) is nearly complete; once it's ready, this issue can be safely closed.

**Comment by silentscar57** [comment]
The front-end is now complete for this feature, this issue will now be closed.
