### ISSUE TITLE
A user-friendly interface for the user of the voice feature 

### ISSUE THREAD

**Issue by KareemOlimi** [rilling/OpenTracks-Winter-2024-COMP-354#66]
**Feature Request:**

We are designing the application to be user-friendly for the user and to enable the user to choose the announcements that they want to receive. This function is designed to increase user interaction.

**Expected Outcome:**

An interface that is smooth and easy to use so that users can easily specify their announcements preferences as well. The system should back them up and then implement them.

**Alternative Solutions:**

Drop-down menu OR Checkbox that facilitates the ease of selecting what the users prefer simply with the click.  Also, to make the options straightforward and simple to apply.

**Completeness / Correctness:**

Ensure that the interface of announcement preferences is user-friendly enough for a bigger audience and convenient enough that users can select their preferences and the system applies these preferences automatically. The satisfaction of the users is sought regularly to enhance this feature.

**Comment by sfnour** [comment]
At sprint 2,  we thought we didn't need to to UI which prompted us to close it. We reopened it, completed some UI and closed once more, but now because it is actually completed.
