### ISSUE TITLE
[Statistics/Overall Season/API] Establish Singleton Pattern for Overall Season Service Functions

### ISSUE THREAD

**Issue by Trim0500** [rilling/OpenTracks-Winter-2024-COMP-354#85]
---
# Feature Request
- Since the overall season statistics needs to be calculate and provided for many parts of the app, it may be fruitful to include a way to access the functions globally. 

# Proposed Solution
- As part of the API interface, a solution would be to utilize the singleton pattern on the service function class that will be created. This way we only have one instance globally and save on needing to create new instances every time a function is required.

# Alternatives
- An Alternative solution would be to make a static class with static functions however this would incur some eager loading at startup whereby the user may/may not use the functions

# Completeness Requirements
- Within the class for the seasonal stats, there exists a private instance variable.
- The method to create/get the instance is made public to whatever needs it.
- The constructor to create the instance is protected.

# Additional context
#5 
---

**Comment by ZaidMinhas** [comment]
Singleton pattern has been established
