### ISSUE TITLE
[Statistics/Overall Season/API] Create Functions to Aggregate Overall Season Stats

### ISSUE THREAD

**Issue by Trim0500** [rilling/OpenTracks-Winter-2024-COMP-354#86]
---
# Feature Request
- As part of the API interface to supply for aggregating seasonal stats, the functions to calculate the seasonal metrics must be made to be able to update to the UI for the stats screen and provide the data to other parts of the app.

# Proposed Solution
- Create separate functions that calculate the following:
    - Total number of runs
    - Total number of ski days
    - Total track distance
    - Total vertical descent
    - Average speed
    - Average slope percentage
- Seeing as how there are a lot of metrics to calculate, it may be in our best interest to utilize a Facade that wraps the functions and returns the output as a collection of values.

# Alternatives
- Alternatively, it may also work to make the metrics calculated in a single function in the class or simply leave it up to the components using an instance to call each method individually. However this may create some tight coupling and poor cohesion.

# Completeness Requirements
- All previously mentioned functions exist and return the respective expected output
- Should the Facacde be used, an implementation of the pattern in the form of an interface class is created

# Additional context
#5 
---

**Comment by Kpytoo** [comment]
Overall statistic service functions where created.
See commit: [c7bfeefd8ae6ca1aaf7e516851fffa58e06f8d74](https://github.com/rilling/OpenTracks-Winter-2024-COMP-354/commit/c7bfeefd8ae6ca1aaf7e516851fffa58e06f8d74)
