### ISSUE TITLE
[Statistics/Overall Season/UI] Create a Preview Element for Key Metrics for All-Time Statistics

### ISSUE THREAD

**Issue by Trim0500** [rilling/OpenTracks-Winter-2024-COMP-354#90]
---
# Feature Request
- It may occur that users of the OpenTracks app need not see all the accumulated seasonal stats but rather want to gloss over them, emphasizing only a few key stats. This could essentially be boiled down to a quality of life request for when users want to quickly grasp these key metrics for comparison or convenience.
- There needs to be a way to show key metrics suck as total KM, total vert and average speed in a small UI element. 

# Proposed Solution
- Seeing as how there will likely be some page listing the seasons and their key stats, implement a list element for all-time stats that is at the top of the page and stays at the top of the page while remaining visible while scrolling.
- Note this will likely need to have some discussions with Group 5 depending on how they are choosing to implement their per season selections for statistics.

# Alternatives
- In this page that shows the different seasons and the key stats, put in an element at the bottom of the page near the return icons that indicates the option to view all the overall stats. 

# Completeness Requirements
- The seasonal stats page contains a way to go to a page that aggregates all the seasonal stats.
- Provided that the proposed solution is the implemented solution, the following key stats are shown (Note that this should have parity with the specific season and which stats they are showing. This may be subject to change)
    - Total KM
    - Total vert
    - Ave. Speed
- When viewing the key metrics shown in the overall seasonal stats page, they are the same as the preview element.
- The numbers shown for the metrics are accurate

# Additional context
### Parent Issue
#7  

### UI
![image](https://github.com/rilling/OpenTracks-Winter-2024-COMP-354/assets/70395022/c7403c53-f88b-4fbf-a61a-82d698bc00af)
---

**Comment by GL34** [comment]
https://github.com/rilling/OpenTracks-Winter-2024-COMP-354/commit/e8ca949ac0c20032c4d06171af1653a01d84a08f
